CREATE TABLE `users`  (
  `id` varchar(16) NOT NULL COMMENT '主键',
  `user_name` varchar(128) NULL COMMENT '用户名',
  `github_id` int(16) NULL COMMENT 'github的id',
  `node_id` varchar(255) NULL COMMENT '用户名',
  `avatar_url` varchar(255) NULL COMMENT '头像',
  `gravatar_id` varchar(255) NULL COMMENT '头像',
  `url` varchar(255) NULL COMMENT '个人信息页',
  `html_url` varchar(255) NULL COMMENT '个人信息页',
  `followers_url` varchar(255) NULL COMMENT '粉丝页',
  `following_url` varchar(255) NULL COMMENT '个人关注页',
  `gists_url` varchar(255) NULL COMMENT 'gists地址',
  `starred_url` varchar(255) NULL COMMENT 'starred地址',
  `subscriptions_url` varchar(255) NULL COMMENT '订阅地址',
  `organizations_url` varchar(255) NULL COMMENT '组织地址',
  `repos_url` varchar(255) NULL COMMENT '用户报告',
  `events_url` varchar(255) NULL COMMENT 'event地址',
  `received_events_url` varchar(255) NULL COMMENT 'received events地址',
  `type` varchar(255) NULL COMMENT '用户类型',
  `site_admin` tinyint(1) NULL COMMENT '是否是管理员',
  `name` varchar(255) NULL COMMENT '姓名',
  `company` varchar(255) NULL COMMENT '公司',
  `blog` varchar(255) NULL COMMENT '个人博客',
  `location` varchar(255) NULL COMMENT '地址',
  `email` varchar(255) NULL COMMENT '邮箱',
  `hireable` varchar(255) NULL COMMENT 'hireable',
  `bio` varchar(255) NULL COMMENT 'bio',
  `public_repos` int(8) NULL COMMENT '公开仓库数',
  `public_gists` int(8) NULL COMMENT '公开gists数',
  `followers` int(8) NULL COMMENT '粉丝数',
  `following` int(8) NULL COMMENT '关注数',
  `created_at` datetime(0) NULL COMMENT '创建时间',
  `updated_at` datetime(0) NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
);


